@echo off
setlocal EnableDelayedExpansion
echo -------------------------------------------------------------------------
echo JWEBSOCKET REPO Deployment Script over FTP
echo (C) Copyright 2013-2015 Innotrade GmbH
echo Author: Victor Antonio Barzana Crespo
echo -------------------------------------------------------------------------
echo           SECTION 1, PREPARING ENVIRONMENT
echo -------------------------------------------------------------------------

if "%JWEBSOCKET_HOME%"=="" goto error
if "%JWEBSOCKET_VER%"=="" goto error
if "%M2_HOME%"=="" goto error
goto start

:error
	echo Environment variable(s) M2_HOME, JWEBSOCKET_HOME and/or JWEBSOCKET_VER not set!
	if "%1"=="/y" goto skipPause1
	pause
:skipPause1
	exit

:start
	rem +-----------------------------------------------------------------------+
	rem |                         DECLARING VARIABLES HERE                      |
	rem +-----------------------------------------------------------------------+
	set CD_SAVE=%CD%
	set CURRENT_YEAR=%DATE:~6,10%
	rem Build Number will be automatically generated
	set NEW_BUILD_NUMBER=%DATE:~9,1%%DATE:~3,2%%DATE:~0,2%
	set /p OLD_BUILD_NUMBER=<%CD%\current_build_number.txt
	set FART=%CD%\tools\fart.exe

:section1_update_svn
	echo.
	echo ------------------------------------------------------------------------
	echo              1- GETTING LATEST CHANGES FROM JWEBSOCKET SVN SERVER
	echo ------------------------------------------------------------------------
	echo.
	echo Updating parent jWebSocket directory: %JWEBSOCKET_HOME%..\..\
	echo.
	svn update %JWEBSOCKET_HOME%../../

:check_build_number
	echo Please check that the following values are correct:
	echo.
	echo 1- BUILD NUMBER: %NEW_BUILD_NUMBER%
	echo ------------------------------------------------------------------------
	echo                    2- CHECKING BUILD NUMBER
	echo ------------------------------------------------------------------------
	if "%1"=="/y" goto skip_prompt_1
	set /p option=Is the autogenerated build number "%NEW_BUILD_NUMBER%" correct (y/n)?
	if /i "%option%" equ "Y" goto replace_build_number
	
	rem build number is not correct
:build_number_incorrect
	set /p option=Please enter the new desired build number and press enter:
	set NEW_BUILD_NUMBER=%option%
	
:skip_prompt_1
:replace_build_number
	echo.
	echo ------------------------------------------------------------------------
	echo      3- REPLACING OLD BUILD NUMBER %OLD_BUILD_NUMBER% BY %NEW_BUILD_NUMBER%
	echo ------------------------------------------------------------------------
	echo Please wait, this process may take a while...
	%FART% -i -r --cvs --svn %JWEBSOCKET_HOME%..\..\branches\*.* %OLD_BUILD_NUMBER% %NEW_BUILD_NUMBER%
	
	rem if second parameter passed as /y it means that we avoid committing changes to subversion
	if "%2"=="/y" goto do_not_commit_to_subversion
	
	echo.
	echo ------------------------------------------------------------------------
	echo   4- UPLOADING CHANGED FILES WITH THE NEW BUILD NUMBER TO SUBVERSION
	echo ------------------------------------------------------------------------
	cd %CD_SAVE%
	rem Now we need to ignore the logs folder and commit the chages to subversion automatically
	echo Ignoring the logs folder NIGHTLY_BUILD_LOGS from being uploaded to subversion
	svn propset svn:ignore NIGHTLY_BUILD_LOGS .
	echo Skipping the file 5_uploadNightlyBuildToFTP.bat because it may have a configured password on it :)
	svn propset svn:ignore 5_uploadNightlyBuildToFTP.bat .
	echo.
	echo The following files have been changed:
	svn status %JWEBSOCKET_HOME%..\..\branches\
	if "%1"=="/y" goto upload_now
	set /p option=Do you really want to upload the changes to our subversion repository (y/n)?
	if /i "%option%" equ "Y" goto upload_now
	goto do_not_commit_to_subversion
:upload_now
	svn commit %JWEBSOCKET_HOME%..\..\branches\ -m "This is an automatic commit generated by our deployment script 0_updateSVNReplaceBuildNumbers.bat in order to put the latest build number %NEW_BUILD_NUMBER% into our repository automatically."
:do_not_commit_to_subversion

:end
if "%1"=="/y" goto skipPause2
pause
:skipPause2