@echo off
setlocal EnableDelayedExpansion
echo -------------------------------------------------------------------------
echo JWEBSOCKET REPO Deployment Script over FTP
echo (C) Copyright 2013-2015 Innotrade GmbH
echo Author: Victor Antonio Barzana Crespo
echo -------------------------------------------------------------------------
echo           SECTION 1, PREPARING ENVIRONMENT
echo -------------------------------------------------------------------------

if "%JWEBSOCKET_HOME%"=="" goto error
if "%JWEBSOCKET_VER%"=="" goto error
if "%M2_HOME%"=="" goto error
goto start

:error
	echo Environment variable(s) M2_HOME, JWEBSOCKET_HOME and/or JWEBSOCKET_VER not set!
	if "%1"=="/y" goto skipPause1
	pause
:skipPause1
	exit

:start
	rem +-----------------------------------------------------------------------+
	rem |                         DECLARING VARIABLES HERE                      |
	rem +-----------------------------------------------------------------------+
	set CD_SAVE=%CD%
	set FTP_HOST=cdn.jwebsocket.org
	set USERNAME=vbarzana
	set PASSWORD=Nabuconodosor1492
	set CURRENT_YEAR=%DATE:~6,10%
	set UPLOADS_DIR=jwebsocket\nightly-builds\%CURRENT_YEAR%
	rem Build Number must be automatically generated
	set BUILD_NUMBER=b%DATE:~9,1%%DATE:~3,2%%DATE:~0,2%
	set DOWNLOADS_DIR=%JWEBSOCKET_HOME%..\..\downloads\jWebSocket-%JWEBSOCKET_VER%\
	set FTP_DEPLOYMENT_LOG_FILE=%2ftp_deployment_results.log
	
	if not exist %DOWNLOADS_DIR% goto missing_downloads_folder
	goto check_build_number
:missing_downloads_folder
	echo Please ensure that the downloads folder %DOWNLOADS_DIR% exist.
	exit
	
:check_build_number
	echo Please check that the following values are correct:
	echo.
	echo 1- BUILD NUMBER: %BUILD_NUMBER%
	echo ------------------------------------------------------------------------
	echo                    1- CHECKING BUILD NUMBER
	echo ------------------------------------------------------------------------
	if "%1"=="/y" goto skipPrompt1
	set /p option=Is the autogenerated build number "%BUILD_NUMBER%" correct (y/n)?
	if /i "%option%" equ "Y" goto check_username
	
	rem build number is not correct
:build_number_incorrect
	set /p option=Please enter the new desired build number and press enter:
	set BUILD_NUMBER=%option%
	
:skipPrompt1	
	echo.
	echo ------------------------------------------------------------------------
	echo                    2- CHECKING USERNAME AND PASSWORD
	echo ------------------------------------------------------------------------
:check_username
	echo.
	echo 2- FTP HOST: %FTP_HOST%
	echo.
	echo 3- REMOTE UPLOAD FOLDER: %UPLOADS_DIR%
	echo.
	echo 4- USERNAME: %USERNAME%
	if NOT "%USERNAME%" equ "" goto check_password

	if "%1"=="/y" goto skipPrompt2
:ask_username
	set /p option=Please enter a username to access to the HOST %FTP_HOST%:
	set USERNAME=%option%

:skipPrompt2
:check_password
	if NOT "%PASSWORD%"=="" goto proceed_to_deployment

if "%1"=="/y" goto skipPrompt3
:ask_password
	set /p option=Please enter the password for the username %USERNAME%:
	set PASSWORD=%option%
	
:skipPrompt3
:proceed_to_deployment
	echo.
	echo ------------------------------------------------------------------------
	echo                3- PROCEEDING WITH THE DEPLOYMENT
	echo ------------------------------------------------------------------------
	
	cd %DOWNLOADS_DIR%
	
	set PACKAGES[1]=jWebSocket-%JWEBSOCKET_VER%.zip
	set PACKAGES[2]=jWebSocketAMQStockTicker-%JWEBSOCKET_VER%.zip
	set PACKAGES[3]=jWebSocketAppSrvDemo-%JWEBSOCKET_VER%.zip
	set PACKAGES[4]=jWebSocketClient-%JWEBSOCKET_VER%.zip
	set PACKAGES[5]=jWebSocketFullSources-%JWEBSOCKET_VER%.zip
	set PACKAGES[6]=jWebSocketJetty-%JWEBSOCKET_VER%.zip
	set PACKAGES[7]=jWebSocketProxy-%JWEBSOCKET_VER%.zip
	set PACKAGES[8]=jWebSocketServer-%JWEBSOCKET_VER%.zip
	set PACKAGES[9]=jWebSocketServer-Bundle-%JWEBSOCKET_VER%.zip
	set PACKAGES[10]=jWebSocketTomcatEngine-%JWEBSOCKET_VER%.zip
	set PACKAGES[11]=jWebSocketWebAppDemo-%JWEBSOCKET_VER%.zip
	set PACKAGES[12]=jWebSocketWindows-%JWEBSOCKET_VER%.zip
	set LENGTH=12
	set FTP_UPLOAD_SCRIPT=jwsFTPUploadScript.dat
	rem Preparing FTP script to be executed
	echo user %USERNAME%>%FTP_UPLOAD_SCRIPT%
	echo %PASSWORD%>>%FTP_UPLOAD_SCRIPT%
	echo mkdir %UPLOADS_DIR%\%BUILD_NUMBER%>>%FTP_UPLOAD_SCRIPT%
	echo cd %UPLOADS_DIR%>>%FTP_UPLOAD_SCRIPT%
	echo put latest_nightly_build.txt>>%FTP_UPLOAD_SCRIPT%
	echo cd %UPLOADS_DIR%\%BUILD_NUMBER%>>%FTP_UPLOAD_SCRIPT%

	for /L %%i in (1,1,%LENGTH%) do (
		if not exist "%DOWNLOADS_DIR%!PACKAGES[%%i]!" (
			echo ERROR: The package !PACKAGES[%%i]! does not exist in the downloads folder, therefore it can't be uploaded, please check.
		)
		echo put !PACKAGES[%%i]!>>%FTP_UPLOAD_SCRIPT%
	)
	echo quit>>%FTP_UPLOAD_SCRIPT%
	echo Executing the FTP deployment script on %FTP_HOST%
	echo Please wait until the deployment finishes the execution...
	echo If you wish to monitorize your upload status, please see the file %DOWNLOADS_DIR%\%FTP_UPLOAD_SCRIPT%...
	ftp -n -s:%FTP_UPLOAD_SCRIPT% %FTP_HOST% > %CD_SAVE%\%FTP_DEPLOYMENT_LOG_FILE%
	echo FTP deployment is complete, please check the file %FTP_DEPLOYMENT_LOG_FILE% for details
	del %FTP_UPLOAD_SCRIPT%
:end
if "%1"=="/y" goto skipPause2
pause
:skipPause2